# Generated by Django 5.0.6 on 2024-06-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='position',
            table='Position',
        ),
    ]
